# Generated by Django 2.0.1 on 2019-03-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_merge_20180115_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
